/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface DailyOrderRecord {
  'quantityDelivered' : number,
  'date' : string,
  'amountCharged' : number,
  'notes' : [] | [string],
  'recordId' : bigint,
  'customerId' : bigint,
}
export interface Delivery {
  'deliveryDate' : Time,
  'deliveryTime' : string,
  'orderId' : bigint,
}
export interface Order {
  'id' : bigint,
  'requestedDeliveryDate' : [] | [Time],
  'status' : string,
  'deliveryDate' : [] | [Time],
  'orderDate' : Time,
  'quantity' : bigint,
  'customerId' : bigint,
  'phoneNumber' : string,
  'product' : Product,
}
export interface Product {
  'id' : bigint,
  'name' : string,
  'quantity' : bigint,
  'price' : bigint,
}
export interface RegularCustomer {
  'pricePerLitre' : number,
  'dailyMilkQuantity' : number,
  'name' : string,
  'lastPaymentDate' : [] | [string],
  'isActive' : boolean,
  'totalAmountDue' : number,
  'address' : string,
  'customerId' : bigint,
  'phone' : string,
  'amountReceived' : number,
}
export type Time = bigint;
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface UserProfile { 'name' : string, 'email' : [] | [string] }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addDailyOrderRecord' : ActorMethod<
    [bigint, string, number, number, [] | [string]],
    bigint
  >,
  'addRegularCustomer' : ActorMethod<
    [string, string, string, number, number],
    bigint
  >,
  'adminLogin' : ActorMethod<[string, string], boolean>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'cancelOrder' : ActorMethod<[bigint], boolean>,
  'changeAdminCredentials' : ActorMethod<[string, string, string], boolean>,
  'deleteDailyOrderRecord' : ActorMethod<[bigint], boolean>,
  'getAllDailyOrderRecords' : ActorMethod<[], Array<DailyOrderRecord>>,
  'getAllOrders' : ActorMethod<[], Array<Order>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getDailyOrderRecordsByCustomer' : ActorMethod<
    [bigint],
    Array<DailyOrderRecord>
  >,
  'getDeliverySchedule' : ActorMethod<[bigint], [] | [Delivery]>,
  'getOrderHistory' : ActorMethod<[bigint], Array<Order>>,
  'getRegularCustomers' : ActorMethod<[], Array<RegularCustomer>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'hasAdminCredentials' : ActorMethod<[], boolean>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'placeOrder' : ActorMethod<
    [bigint, Product, bigint, string, [] | [Time]],
    bigint
  >,
  'recordDailyDelivery' : ActorMethod<[bigint], boolean>,
  'recordPayment' : ActorMethod<[bigint, number, string], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'scheduleDelivery' : ActorMethod<[bigint, Time, string], boolean>,
  'setAdminCredentials' : ActorMethod<[string, string], boolean>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'updateOrderStatus' : ActorMethod<[bigint, string], boolean>,
  'updateRegularCustomer' : ActorMethod<
    [bigint, string, string, string, number, number, boolean],
    boolean
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];