/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const DailyOrderRecord = IDL.Record({
  'quantityDelivered' : IDL.Float64,
  'date' : IDL.Text,
  'amountCharged' : IDL.Float64,
  'notes' : IDL.Opt(IDL.Text),
  'recordId' : IDL.Nat,
  'customerId' : IDL.Nat,
});
export const Time = IDL.Int;
export const Product = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'quantity' : IDL.Nat,
  'price' : IDL.Nat,
});
export const Order = IDL.Record({
  'id' : IDL.Nat,
  'requestedDeliveryDate' : IDL.Opt(Time),
  'status' : IDL.Text,
  'deliveryDate' : IDL.Opt(Time),
  'orderDate' : Time,
  'quantity' : IDL.Nat,
  'customerId' : IDL.Nat,
  'phoneNumber' : IDL.Text,
  'product' : Product,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Opt(IDL.Text),
});
export const Delivery = IDL.Record({
  'deliveryDate' : Time,
  'deliveryTime' : IDL.Text,
  'orderId' : IDL.Nat,
});
export const RegularCustomer = IDL.Record({
  'pricePerLitre' : IDL.Float64,
  'dailyMilkQuantity' : IDL.Float64,
  'name' : IDL.Text,
  'lastPaymentDate' : IDL.Opt(IDL.Text),
  'isActive' : IDL.Bool,
  'totalAmountDue' : IDL.Float64,
  'address' : IDL.Text,
  'customerId' : IDL.Nat,
  'phone' : IDL.Text,
  'amountReceived' : IDL.Float64,
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addDailyOrderRecord' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Float64, IDL.Float64, IDL.Opt(IDL.Text)],
      [IDL.Nat],
      [],
    ),
  'addRegularCustomer' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Float64, IDL.Float64],
      [IDL.Nat],
      [],
    ),
  'adminLogin' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], ['query']),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'cancelOrder' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'changeAdminCredentials' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text],
      [IDL.Bool],
      [],
    ),
  'deleteDailyOrderRecord' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'getAllDailyOrderRecords' : IDL.Func(
      [],
      [IDL.Vec(DailyOrderRecord)],
      ['query'],
    ),
  'getAllOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getDailyOrderRecordsByCustomer' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(DailyOrderRecord)],
      ['query'],
    ),
  'getDeliverySchedule' : IDL.Func([IDL.Nat], [IDL.Opt(Delivery)], ['query']),
  'getOrderHistory' : IDL.Func([IDL.Nat], [IDL.Vec(Order)], ['query']),
  'getRegularCustomers' : IDL.Func([], [IDL.Vec(RegularCustomer)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'hasAdminCredentials' : IDL.Func([], [IDL.Bool], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'placeOrder' : IDL.Func(
      [IDL.Nat, Product, IDL.Nat, IDL.Text, IDL.Opt(Time)],
      [IDL.Nat],
      [],
    ),
  'recordDailyDelivery' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'recordPayment' : IDL.Func([IDL.Nat, IDL.Float64, IDL.Text], [IDL.Bool], []),
  'resetAdminPassword' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text],
      [IDL.Bool],
      [],
    ),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'scheduleDelivery' : IDL.Func([IDL.Nat, Time, IDL.Text], [IDL.Bool], []),
  'setAdminCredentials' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'updateOrderStatus' : IDL.Func([IDL.Nat, IDL.Text], [IDL.Bool], []),
  'updateRegularCustomer' : IDL.Func(
      [
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Float64,
        IDL.Float64,
        IDL.Bool,
      ],
      [IDL.Bool],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const DailyOrderRecord = IDL.Record({
    'quantityDelivered' : IDL.Float64,
    'date' : IDL.Text,
    'amountCharged' : IDL.Float64,
    'notes' : IDL.Opt(IDL.Text),
    'recordId' : IDL.Nat,
    'customerId' : IDL.Nat,
  });
  const Time = IDL.Int;
  const Product = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'quantity' : IDL.Nat,
    'price' : IDL.Nat,
  });
  const Order = IDL.Record({
    'id' : IDL.Nat,
    'requestedDeliveryDate' : IDL.Opt(Time),
    'status' : IDL.Text,
    'deliveryDate' : IDL.Opt(Time),
    'orderDate' : Time,
    'quantity' : IDL.Nat,
    'customerId' : IDL.Nat,
    'phoneNumber' : IDL.Text,
    'product' : Product,
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Opt(IDL.Text),
  });
  const Delivery = IDL.Record({
    'deliveryDate' : Time,
    'deliveryTime' : IDL.Text,
    'orderId' : IDL.Nat,
  });
  const RegularCustomer = IDL.Record({
    'pricePerLitre' : IDL.Float64,
    'dailyMilkQuantity' : IDL.Float64,
    'name' : IDL.Text,
    'lastPaymentDate' : IDL.Opt(IDL.Text),
    'isActive' : IDL.Bool,
    'totalAmountDue' : IDL.Float64,
    'address' : IDL.Text,
    'customerId' : IDL.Nat,
    'phone' : IDL.Text,
    'amountReceived' : IDL.Float64,
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addDailyOrderRecord' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Float64, IDL.Float64, IDL.Opt(IDL.Text)],
        [IDL.Nat],
        [],
      ),
    'addRegularCustomer' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Float64, IDL.Float64],
        [IDL.Nat],
        [],
      ),
    'adminLogin' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], ['query']),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'cancelOrder' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'changeAdminCredentials' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [IDL.Bool],
        [],
      ),
    'deleteDailyOrderRecord' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'getAllDailyOrderRecords' : IDL.Func(
        [],
        [IDL.Vec(DailyOrderRecord)],
        ['query'],
      ),
    'getAllOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getDailyOrderRecordsByCustomer' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(DailyOrderRecord)],
        ['query'],
      ),
    'getDeliverySchedule' : IDL.Func([IDL.Nat], [IDL.Opt(Delivery)], ['query']),
    'getOrderHistory' : IDL.Func([IDL.Nat], [IDL.Vec(Order)], ['query']),
    'getRegularCustomers' : IDL.Func([], [IDL.Vec(RegularCustomer)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'hasAdminCredentials' : IDL.Func([], [IDL.Bool], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'placeOrder' : IDL.Func(
        [IDL.Nat, Product, IDL.Nat, IDL.Text, IDL.Opt(Time)],
        [IDL.Nat],
        [],
      ),
    'recordDailyDelivery' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'recordPayment' : IDL.Func(
        [IDL.Nat, IDL.Float64, IDL.Text],
        [IDL.Bool],
        [],
      ),
    'resetAdminPassword' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [IDL.Bool],
        [],
      ),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'scheduleDelivery' : IDL.Func([IDL.Nat, Time, IDL.Text], [IDL.Bool], []),
    'setAdminCredentials' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'updateOrderStatus' : IDL.Func([IDL.Nat, IDL.Text], [IDL.Bool], []),
    'updateRegularCustomer' : IDL.Func(
        [
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Float64,
          IDL.Float64,
          IDL.Bool,
        ],
        [IDL.Bool],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };