/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface http_request_result {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export interface TransformationOutput {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export type Time = bigint;
export interface TransformationInput {
    context: Uint8Array;
    response: http_request_result;
}
export interface Delivery {
    deliveryDate: Time;
    deliveryTime: string;
    orderId: bigint;
}
export interface Order {
    id: bigint;
    status: string;
    deliveryDate?: Time;
    orderDate: Time;
    quantity: bigint;
    customerId: bigint;
    phoneNumber: string;
    product: Product;
}
export interface Product {
    id: bigint;
    name: string;
    quantity: bigint;
    price: bigint;
}
export interface http_header {
    value: string;
    name: string;
}
export interface backendInterface {
    cancelOrder(orderId: bigint): Promise<boolean>;
    getDeliverySchedule(orderId: bigint): Promise<Delivery | null>;
    getOrderHistory(customerId: bigint): Promise<Array<Order>>;
    placeOrder(customerId: bigint, product: Product, quantity: bigint, phoneNumber: string): Promise<bigint>;
    scheduleDelivery(orderId: bigint, deliveryDate: Time, deliveryTime: string): Promise<boolean>;
    transform(input: TransformationInput): Promise<TransformationOutput>;
    updateOrderStatus(orderId: bigint, newStatus: string): Promise<boolean>;
}
import type { Delivery as _Delivery, Order as _Order, Product as _Product, Time as _Time } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async cancelOrder(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.cancelOrder(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.cancelOrder(arg0);
            return result;
        }
    }
    async getDeliverySchedule(arg0: bigint): Promise<Delivery | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getDeliverySchedule(arg0);
                return from_candid_opt_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDeliverySchedule(arg0);
            return from_candid_opt_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async getOrderHistory(arg0: bigint): Promise<Array<Order>> {
        if (this.processError) {
            try {
                const result = await this.actor.getOrderHistory(arg0);
                return from_candid_vec_n2(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOrderHistory(arg0);
            return from_candid_vec_n2(this._uploadFile, this._downloadFile, result);
        }
    }
    async placeOrder(arg0: bigint, arg1: Product, arg2: bigint, arg3: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.placeOrder(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.placeOrder(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async scheduleDelivery(arg0: bigint, arg1: Time, arg2: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.scheduleDelivery(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.scheduleDelivery(arg0, arg1, arg2);
            return result;
        }
    }
    async transform(arg0: TransformationInput): Promise<TransformationOutput> {
        if (this.processError) {
            try {
                const result = await this.actor.transform(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.transform(arg0);
            return result;
        }
    }
    async updateOrderStatus(arg0: bigint, arg1: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateOrderStatus(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateOrderStatus(arg0, arg1);
            return result;
        }
    }
}
function from_candid_Order_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Order): Order {
    return from_candid_record_n4(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Delivery]): Delivery | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Time]): Time | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: string;
    deliveryDate: [] | [_Time];
    orderDate: _Time;
    quantity: bigint;
    customerId: bigint;
    phoneNumber: string;
    product: _Product;
}): {
    id: bigint;
    status: string;
    deliveryDate?: Time;
    orderDate: Time;
    quantity: bigint;
    customerId: bigint;
    phoneNumber: string;
    product: Product;
} {
    return {
        id: value.id,
        status: value.status,
        deliveryDate: record_opt_to_undefined(from_candid_opt_n5(_uploadFile, _downloadFile, value.deliveryDate)),
        orderDate: value.orderDate,
        quantity: value.quantity,
        customerId: value.customerId,
        phoneNumber: value.phoneNumber,
        product: value.product
    };
}
function from_candid_vec_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Order>): Array<Order> {
    return value.map((x)=>from_candid_Order_n3(_uploadFile, _downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
